grep BLCA instance.minus.txt | awk '{print $8}' | sort | head -1
grep BRCA instance.minus.txt | awk '{print $8}' | sort | head -1
grep CHOLLIHC instance.minus.txt | awk '{print $8}' | sort | head -1
grep COADREAD instance.minus.txt | awk '{print $8}' | sort | head -1
grep ESCASTAD instance.minus.txt | awk '{print $8}' | sort | head -1
grep HNSC instance.minus.txt | awk '{print $8}' | sort | head -1
grep KICHKIRCKIRP instance.minus.txt | awk '{print $8}' | sort | head -1
grep LUADLUSC instance.minus.txt | awk '{print $8}' | sort | head -1
grep PRAD instance.minus.txt | awk '{print $8}' | sort | head -1
grep THCA instance.minus.txt | awk '{print $8}' | sort | head -1
